<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Products\Products.API\Products.API.csproj" />
    <ProjectReference Include="..\..\Inventory\Inventory.API\Inventory.API.csproj" />
    <ProjectReference Include="..\..\Orders\Orders.API\Orders.API.csproj" />
    <ProjectReference Include="..\..\Products\Products.Infrastructure\Products.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Inventory\Inventory.Infrastructure\Inventory.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Orders\Orders.Infrastructure\Orders.Infrastructure.csproj" />
  </ItemGroup>

</Project>
